# Generated by Django 3.0.4 on 2020-04-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loom1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_id', models.CharField(default=0, max_length=50)),
                ('meter', models.IntegerField(default=0)),
                ('wdr', models.IntegerField(default=0)),
                ('wdt', models.IntegerField(default=0)),
                ('cm', models.IntegerField(default=0)),
                ('cwp', models.IntegerField(default=0)),
                ('sos', models.IntegerField(default=0)),
                ('sv', models.IntegerField(default=0)),
                ('date_modified', models.DateField(auto_now=True)),
                ('time_modified', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='faulttable',
            name='time_modified',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='primarytable',
            name='time_modified',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faulttable',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='primarytable',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
