# Generated by Django 3.0.4 on 2020-04-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loom1', '0002_auto_20200419_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastertable',
            old_name='cm',
            new_name='cm_count',
        ),
        migrations.RenameField(
            model_name='mastertable',
            old_name='cwp',
            new_name='cwp_count',
        ),
        migrations.RenameField(
            model_name='mastertable',
            old_name='sos',
            new_name='sos_count',
        ),
        migrations.RenameField(
            model_name='mastertable',
            old_name='sv',
            new_name='sv_count',
        ),
        migrations.RenameField(
            model_name='mastertable',
            old_name='wdr',
            new_name='wdr_count',
        ),
        migrations.RenameField(
            model_name='mastertable',
            old_name='wdt',
            new_name='wdt_count',
        ),
    ]
